### ISSUE TITLE
Profile Manager: Add a message to indicate that the mnemonic is valid

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/playground#82]
### Description

Add a message to confirm that the mnemonic is valid once the validation is done. the purpose of this message is to add an indication that the validation is done and that the user is ready to login.

### Implementation

- Once the loading of the mnemonic validation is done a message should appear mentioning that the mnemonic is valid (preferably in green).
- The message should appear in the same place as the error message (under the mnemonic field) as seen in the screenshot below.

   ![image](https://github.com/threefoldtech/playground/assets/101194226/2015afbd-607d-4db7-9659-2c2d85cddd60)

**Comment by zaelgohary** [comment]
Added a new hint in the mnemonic field but it doesn't reflect. I'm trying to find another way without affecting other inputs as all use the same custom field.

**Comment by A-Harby** [comment]
Verified.

Message was added to indicate the mnemonic validation.

![image](https://github.com/threefoldtech/playground/assets/109473873/d0c6f9c4-434e-464a-9d94-5ae0e909becc)

![image](https://github.com/threefoldtech/playground/assets/109473873/ce655b4b-407c-476d-ac4f-b87dab532b8d)
